# ---
# uuid: 019de241-9889-7c2c-94a5-4de78ccb2cc7
# dotenv.public.key: 02054a69d217d6c7af9868d5613650e149b35b0fb2d9acbef7989d67f38c360d13
# ---
default = "v1.5.3"

# profile of default
[profile.default]
description = "Default profile for duckdb"
settings = { default_order = "ASCENDING" }

[profile.default.quack_server]
uri = "quack:localhost"
token = "super_secret"

# secret
[profile.default.secret.hf]
type = "http"
BEARER_TOKEN = "xxx"
VERIFY_SSL = 0
EXTRA_HTTP_HEADERS = { "X-Custom-Header" = "value" }

[profile.default.secret.rest]
sql = '''
CREATE SECRET http_auth (
    TYPE http,
    BEARER_TOKEN 'token'
);
'''

# bucket
[profile.default.bucket.s3mock]
type = "s3"
KEY_ID = 'my_secret_key1'
SECRET = 'my_secret_value1'
endpoint = "127.0.0.1:19090"
URL_STYLE = 'path'
USE_SSL = false
REGION = 'us-east-1'
SCOPE = 's3://my-bucket'

[profile.default.bucket.alioss]
TYPE = "s3"
KEY_ID = 'my_secret_key1'
SECRET = 'my_secret_value1'
ENDPOINT = 'oss-cn-hangzhou.aliyuncs.com'
URL_STYLE = 'vhost'
REGION = "oss-cn-hangzhou"
SCOPE = 's3://oss-bucket'

# profile of polyglot
[profile.polyglot]
description = "Add different files support"
duckdb_version = "v1.5.2"
extensions = ["parquet", "excel", "quack"]

[profile.polyglot.environment]
nick = "Jackie"

[profile.polyglot.attached.mydb]
path = "host=localhost user=root port=0 database=mysql"
type = "mysql"

[profile.polyglot.attached.encrypted]
path = "encrypted.duckdb"
options = { ENCRYPTION_KEY = "xxx" }