const DUCKDB_VERSIONS: [&str; 3] = ["v1.4.4", "v1.5.1", "v1.5.2"];

const DUCKDB_CORE_EXTENSIONS: [&str; 28] = [
    "autocomplete",
    "avro",
    "aws",
    "azure",
    "delta",
    "ducklake",
    "encodings",
    "excel",
    "fts",
    "httpfs",
    "iceberg",
    "icu",
    "inet",
    "jemalloc",
    "json",
    "lance",
    "motherduck",
    "mysql",
    "parquet",
    "postgres",
    "spatial",
    "sqlite",
    "tpcds",
    "tpch",
    "unity_catalog",
    "ui",
    "vortex",
    "vss",
];
